name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
          type: choice
          options:
            - first test
            - second test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install
    - name: Run first test
      if: "github.event.inputs.deployment_target == 'first_test'"
      run: tests/test_f.py::test_wiki1[chromium]
    - name: Run second test
      if: "github.event.inputs.deployment_target == 'second_test'"
      run: tests/test_f.py::test_wiki2[chromium]
