name: Playwright Tests

on:
      repository_dispatch:
#        types: [ "my_custom_event" ]

jobs:
  handle_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Log webhook payload
        run: |
          echo "Received webhook event!"
          echo "Event Type: ${{ github.event.action }}"
          echo "Payload: ${{ github.event.client_payload | toJson }}"

#  test:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.11'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#    - name: Ensure browsers are installed
#      run: python -m playwright install
#    - name: Run your tests
#      run: pytest --tracing=retain-on-failure
